# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions 
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        #node-version: [12.x, 14.x, 16.x]
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag matts-lackluster-app:latest

    - name: Scan container images for vulnerabitilies using Lacework
      uses: timarenz/lw-scanner-action@v0.3.0
      env:
        LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }} 
        LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
        LW_SCANNER_SCAN_LIBRARY_PACKAGES: true
      with:
        image_name: matts-lackluster-app
        image_tag: latest
        save_html_report: true

    - name: Checkout bidnessforb/sarif-integration
      if: always()
      uses: actions/checkout@v2
      with:
       repository: BidnessForB/sarif-integration
       ref: refs/heads/ipcrm-action
       path: ./.github/actions/lw-scanner-sarif-converter

    - uses: ./.github/actions/lw-scanner-sarif-converter
      if: always()
      name: Covnert scan result to SARIF

    - name: 'Upload build artifact'
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: build-html-artifact
        path: |
          **/*.html
        retention-days: 5

    - name: 'Upload sarif artifact'
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: upload-sarif-artifact
        path: |
          **/*.sarif.json
        retention-days: 5

    - name: 'Tail test'
      if: always()
      run: |
        tail './report.sarif.json'


    - name: Upload SARIF file
      if: always()
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: './report.sarif.json'
